# Generated by Django 5.1.7 on 2025-04-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_applicant_remove_order_customer_resume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('salary', models.FloatField()),
                ('number_of_responses', models.IntegerField()),
                ('company', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
    ]
